# Problem 1

In [1]:
import numpy as np

# 2 - 0 ile 10 arasında 5 sayıdan oluşan matris üretin
matrix = np.random.randint(0, 10, size=(1, 5))
print("Matrix:", matrix)

# 3 - Matris'in boyutunu öğrenin
matrixShape = matrix.shape
print("Matrix'in boyutu:", matrixShape)

# 4 - Matris'i yeniden boyutlandırın
reshapedMatrix = matrix.reshape(5, 1)
print("Yeniden boyutlandırılmış matrix:", reshapedMatrix)

# 5 - Matris'in boyut sayısını öğrenin
numDimensions = reshapedMatrix.ndim
print("Yeniden boyutlandırılmış matrix'in boyut sayısı:", numDimensions)

Matrix: [[7 2 5 2 2]]
Matrix'in boyutu: (1, 5)
Yeniden boyutlandırılmış matrix: [[7]
 [2]
 [5]
 [2]
 [2]]
Yeniden boyutlandırılmış matrix'in boyut sayısı: 2


# Problem 2

In [2]:
import numpy as np
# 1 - 0 ile 10 arasında bulunan tek sayılardan oluşan matris üretin
matrix = np.random.choice(np.arange(1, 10, 2), size=(3, 3)) # Örnek olarak 3x3 boyutunda matris
print("Matrix:\n", matrix)
# 2 - Oluşturduğunuz matrisi parçalayın
splitMatrices = np.hsplit(matrix, 3)
print("Parçalanmış Matrisler:")
for i, part in enumerate(splitMatrices):
    print(f"Part {i+1}:\n", part)
# 3 - Parçalanmış matrisleri birleştirin
reconstructedMatrix = np.hstack(splitMatrices)
print("Birleştirilmiş Matrix:\n", reconstructedMatrix)

Matrix:
 [[5 9 7]
 [9 7 9]
 [5 5 5]]
Parçalanmış Matrisler:
Part 1:
 [[5]
 [9]
 [5]]
Part 2:
 [[9]
 [7]
 [5]]
Part 3:
 [[7]
 [9]
 [5]]
Birleştirilmiş Matrix:
 [[5 9 7]
 [9 7 9]
 [5 5 5]]


# Problem 3

In [3]:
import numpy as np
# 1 - 5 ile 100 arasında ikişer ikişer atlayarak rastgele 10 sayıdan oluşan matris üretin
matrix = np.random.choice(np.arange(5, 101, 2), size=10)
print("Matrix:", matrix)

# 2 - Matris'in özelliklerini inceleyin
numDimensions = matrix.ndim
print("Matris'in boyut sayısı:", numDimensions)

shape = matrix.shape
print("Matris'in şekli:", shape)

size = matrix.size
print("Matris'teki toplam eleman sayısı:", size)

dataType = matrix.dtype
print("Matris'in veri tipi:", dataType)



Matrix: [45 23 23 95 29 21  9 25 25  7]
Matris'in boyut sayısı: 1
Matris'in şekli: (10,)
Matris'teki toplam eleman sayısı: 10
Matris'in veri tipi: int64
